# Generated by Django 2.2.4 on 2020-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='decribe',
            field=models.TextField(default='Yo', max_length=200),
        ),
    ]
