# Generated by Django 2.2.4 on 2020-12-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_files_decribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='decribe',
            new_name='describe',
        ),
    ]
