# Generated by Django 2.2.4 on 2020-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20201201_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.FileField(upload_to='csvs'),
        ),
    ]
