# Generated by Django 2.2.4 on 2020-12-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_auto_20201202_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
