# Generated by Django 2.2.4 on 2020-12-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20201204_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
