# Generated by Django 2.2.4 on 2020-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_files_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.FileField(upload_to='media'),
        ),
    ]
