# Generated by Django 2.2.4 on 2020-12-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20201201_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user_name',
        ),
    ]
