# Generated by Django 2.2.4 on 2020-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_results_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='Info',
        ),
        migrations.AddField(
            model_name='recommend',
            name='general',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recommend',
            name='host_level',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recommend',
            name='in_the_organisation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recommend',
            name='recommended_steps',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recommend',
            name='server_level',
            field=models.TextField(default=''),
        ),
    ]
