# Generated by Django 2.2.4 on 2020-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Results',
            new_name='Result',
        ),
        migrations.AddField(
            model_name='results',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
